### ISSUE TITLE
SecurityConfig类中是HttpSecurity httpSecurity 参数在IDEA中有红线

### ISSUE THREAD

**Issue by ChenQuan5** [lhing17/gsein-platform#3]
在类上加入@EnableWebSecurity可以消除红线
如下所示
@Configuration
@EnableWebSecurity
public class SecurityConfig

**Comment by lhing17** [comment]
在spring-boot-autoconfigure包的SpringBootWebSecurityConfiguration类中已经包含了该注解，只要classpath中包含了Spring security就会生效。在我这边运行也没有红线，请检查一下自己的配置。
